spring:
  redis:
    host: localhost
    port: 6379
  mvc:
    throw-exception-if-no-handler-found: true
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true


  #文件配置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/self_discipline?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl